var success_msg = {
  registered: "User registered successfully",
  login: "Login successful",
  passwordLink: "Password reset link has been sent to your email",
  passwordChange: "Password changed successfully",
  logout: "User logged out successfully!",
  updateProfile: "User profile updated successfully!",
  passwordUpdate: "Password updated successfully.",
  otpSend: "OTP sent successfully",
  otpVerify: "Otp verified successfully",
  otpResend: "OTP resent successfully",
  notificationList: "Notification list fetched successfully",
  churchesFound: "Churches found successfully",
  bannerList: "Banner list fetched successfully",
  needPost: "Need posted successfully",
  needPostList: "Need post list fetched successfully",
  needPostComment: "Comment on need post added successfully",
  needPostCommentList: "Comment on need post list fetched successfully",
  likeNeedPost: "Like on need post added successfully",
  likeNeedPostList: "Like on need post list fetched successfully",
  unLikeNeedPost: "Unlike on need post added successfully",
  testimonyPost: "Testimony posted successfully",
  testimonyPostList: "Testimony post list fetched successfully",
  testimonyPostComment: "Comment on testimony post added successfully",
  testimonyPostCommentList:
    "Comment on testimony post list fetched successfully",
  likeTestimonyPost: "Like on testimony post added successfully",
  likeTestimonyPostList: "Like on testimony post list fetched successfully",
  unLikeTestimonyPost: "Unlike on testimony post added successfully",

  logoUploadSuccess: "Logo uploaded successfully",
  addVideo:"Video added successfully",
  videoList:"Video list fetched successfully",
  unLikeVideo:"Unlike on video added successfully",
  likeVideo:"Like on video added successfully",
  commentVideo:"Comment on video added successfully",
  commentVideoList:"Comment on video list fetched successfully",
  createEvent:"Event created successfully",
  eventList:"Event list fetched successfully",
  createGroup:"Group created successfully",
  groupList:"Group list fetched successfully",
  likeGroup:"Like on group added successfully",
  unLikeGroup:"Unlike on group added successfully",
  commentGroup:"Comment on group added successfully",
  commentGroupList:"Comment on group list fetched successfully",
  likeGroupList:"Like on group list fetched successfully",
  myGroupList:"My group list fetched successfully",
  groupDetail:"Group detail fetched successfully",
  joinGroup:"Group joined successfully",
  groupMemberList:"Group member list fetched successfully",
  nonProfileUserList:"Non profile user list fetched successfully",
  addFeed:"Feed added successfully",
  feedList:"Feed list fetched successfully",
  likeFeed:"Like on feed added successfully",
  unlikeFeed:"Unlike on feed added successfully",
  likeFeedList:"Like on feed list fetched successfully",
  commentOnFeed:"Comment on feed added successfully",
  commentOnFeedList:"Comment on feed list fetched successfully",
  getFollowList:"Follow list fetched successfully",
  followUser:"User followed successfully",
  unfollowUser:"User unfollowed successfully",
  getDailyBreadList:"Daily bread list fetched successfully",
  getDailyBreadDetail:"Daily bread detail fetched successfully",
  commentAdded:"Comment add succssfully",
  commentList:"Comment list get successfully",
  likeDailyBreadAdded:"Like daily bread successfully",
  unlikeDailyBreadAdded:"Unlike daily bread successfully.",
  likeDailyBreadList:"Like daily bread list succssfully",
  getDailyPrayerList:"Daily Prayer list fetched successfully.",
  getDailyPrayerDetail:"Daily Prayer detail fetched successfully.",
  likeDailyPrayerAdded:"Like daily Prayer successfully",
  unlikeDailyPrayerAdded:"Unlike daily Prayer successfully.",
  likeDailyPrayerList:"Like daily Prayer list get successfully",
  groupPost:"Group post add scussfully",
  userTraitAndExpList: "User trait and experience list fetched successfully",
  userTypeOfBusList: "User type of business list fetched successfully",
  groupFilterType: "Group filter type fetched successfully",
};

var failed_msg = {
  emailAlreadyExists: "Email already exists!",
  phoneNumberAlreadyExists: "Phone number already exists!",
  userNotFound: "User not found",
  invalidPassword: "Invalid password",
  noAccWEmail: "No account exists with this email",
  pwdNoMatch: "Passwords do not match!",
  userIdReq: "User ID is required.",
  incorrectCurrPwd: "Incorrect current password.",
  tokReq: "Token is required!",
  invTok: "Invalid token!",
};

var error_msg = {
  regUser: "Error registering user",
  loguser: "Error during login",
  forgPwdErr: "Forgot password error",
  resetPwdErr: "Reset password error",
  chngPwdErr: "Error while changing the password",
  logoutErr: "Logout error",
  updPrfErr: "Error while updating profile",
  tokenNotPrv: "Token is not provided!",
  forPwdTokVer: "Forgot password token verification error!",
  pwdResTokExp: "Password reset token is invalid or has expired",
  otpSendErr: "Error while sending the otp",
  otpVerErr: "Error while verifying the otp",
  otpResErr: "Failed to resend OTP",
  invalidPhoneNumber: "Invalid phone number",
  errUploadLogo: "Error uploading logo",
  internalServerError: "Internal server error",
};

module.exports = {
  success_msg: success_msg,
  failed_msg: failed_msg,
  error_msg: error_msg,
};
