const Sequelize = require("sequelize");
const sequelize = require("../dbConnection").sequelize;

module.exports = {
  userModel: require("./userModel")(Sequelize, sequelize, Sequelize.DataTypes),
  cmsModel: require("./cmsModel")(Sequelize, sequelize, Sequelize.DataTypes),
  notificationModel:require("./notificationModels")(Sequelize, sequelize, Sequelize.DataTypes),
  contactUsModel:require("./contactUs")(Sequelize, sequelize, Sequelize.DataTypes),
  subscriptionModel:require("./subscriptionModel")(Sequelize, sequelize, Sequelize.DataTypes),
  bannerModel:require("./bannerModel")(Sequelize, sequelize, Sequelize.DataTypes),
  heartToServeModel:require("./heartToServeModel")(Sequelize, sequelize, Sequelize.DataTypes),
  maritalStatusModel:require("./maritalStatusModel")(Sequelize, sequelize, Sequelize.DataTypes),
  numberOfMembersModel:require("./numberOfMembersModel")(Sequelize, sequelize, Sequelize.DataTypes),
  profilePreferenceModel:require("./profilePreferenceModel")(Sequelize, sequelize, Sequelize.DataTypes),
  traitsExperienceModel:require("./traitsExperienceModel")(Sequelize, sequelize, Sequelize.DataTypes),
  needPostModel:require("./needPostModel")(Sequelize, sequelize, Sequelize.DataTypes),
  commentNeedPostModel:require("./commentNeedModel")(Sequelize, sequelize, Sequelize.DataTypes),
  likeNeedPostModel:require("./likeNeedPostModel")(Sequelize, sequelize, Sequelize.DataTypes),
  testimonyPostModel:require("./testimonyPostModel")(Sequelize, sequelize, Sequelize.DataTypes),
  commentTestimonyModel:require("./commentTestimonyModel")(Sequelize, sequelize, Sequelize.DataTypes),
  likeTestimonyModel:require("./likeTestimonyPost")(Sequelize, sequelize, Sequelize.DataTypes),
  filterTestimoniesModel:require("./filterTestimoniesModel")(Sequelize, sequelize, Sequelize.DataTypes),
  videoModel:require("./videoModel")(Sequelize, sequelize, Sequelize.DataTypes),
  commentVideoModel:require("./commentVideoModels")(Sequelize, sequelize, Sequelize.DataTypes),
  likeVideoModel:require("./likeVideoModels")(Sequelize, sequelize, Sequelize.DataTypes),
  eventModel:require("./eventModel")(Sequelize, sequelize, Sequelize.DataTypes),
  groupModel:require("./groupModel")(Sequelize, sequelize, Sequelize.DataTypes),
  likeGroupModel:require("./likeGroupModel")(Sequelize, sequelize, Sequelize.DataTypes),
  commentGroupModel:require("./commentGroupModel")(Sequelize, sequelize, Sequelize.DataTypes),
  groupMemberModel:require("./groupMemberModel")(Sequelize, sequelize, Sequelize.DataTypes),
  groupPostModel:require("./groupPostModel")(Sequelize, sequelize, Sequelize.DataTypes),
  chatConstantModel:require("./chatConstantModel")(Sequelize, sequelize, Sequelize.DataTypes),
  messageModel:require("./messageModel")(Sequelize, sequelize, Sequelize.DataTypes),
  addFeedModel:require("./addFeedModel")(Sequelize, sequelize, Sequelize.DataTypes),
  likeFeedModel:require("./likeFeedModel")(Sequelize, sequelize, Sequelize.DataTypes),
  commentFeedModel:require("./commentFeedModel")(Sequelize, sequelize, Sequelize.DataTypes),
  followingModel:require("./followingModel")(Sequelize, sequelize, Sequelize.DataTypes),
  dailyBreadModel: require("./dailyBreadModel")(Sequelize, sequelize, Sequelize.DataTypes),
  dailyBreadCommentModel: require("./dailyBreadCommentModel")(Sequelize, sequelize, Sequelize.DataTypes),
  likeDailyBreadModel: require("./likeDailyBreadModel")(Sequelize, sequelize, Sequelize.DataTypes),
  prayerRequestModel: require("./prayerRequestModel")(Sequelize, sequelize, Sequelize.DataTypes),
  prayerRequestCommentModel: require("./prayerRequestCommentModel")(Sequelize, sequelize, Sequelize.DataTypes),
  likePrayerRequestModel: require("./likePrayerRequestModel")(Sequelize, sequelize, Sequelize.DataTypes),
  groupFilter: require("./groupFilterModel")(Sequelize, sequelize, Sequelize.DataTypes),
  businessTypeModel: require("./businessTypeModel")(Sequelize, sequelize, Sequelize.DataTypes),
  eventTypeModel: require("./eventTypeModel")(Sequelize, sequelize, Sequelize.DataTypes),

};
 